naviation functionality
saiumesh535/angular-zero-config pull request #5
Opened 2018-06-06 16:51 UTC by saiumesh535

1. added search functionality of metadata in navigation.

2018-06-06 16:52 UTC, saiumesh535 commented on src/app/navigation/navigation.component.ts
> +    this.store.pipe(select(selectTopicsFromState)).subscribe(lol => {
add ngunsubscibe so it unsubscribe on destroy

2018-06-06 16:54 UTC, saiumesh535 commented on src/app/navigation/navigation.component.ts
> +    this.store.pipe(select(selectTopicsFromState)).subscribe(lol => {
Done.

2018-06-07 02:28 UTC, lava-dukanam requested changes

2018-06-07 02:28 UTC, Lava-Dukanam commented on src/app/navigation/navigation.component.ts
> +      takeUntil(this.ngUnSubScribe),
You could actually abstract this out into some base component and extend every component from it

move the subject creation part to base component and implement onDestroy there

2018-08-06 10:43 UTC, merged